apiVersion: v1
kind: Service

metadata:
  name: ddd-ordering-canary
  namespace: ddd

spec:
  selector:
    app: ddd-ordering
    track: canary

  ports:
    - name: http
      port: 8081
      targetPort: 8081